[package]
name = "milu"
version = "0.2.1"
edition = "2018"

[dependencies]
nom = "7"
nom_locate = "4.0.0"
regex = "1"
easy-error = "1"
log = "0.4"

[dev-dependencies]
clap = "~3.2"
rustyline = "9"
rustyline-derive = "0.7.0"
nix = "0.24.2"
