[package]
name = "milu"
version = "0.2.1"
edition = "2018"

[dependencies]
nom = "7"
nom_locate = "4.1.0"
regex = "1"
easy-error = "1"
tracing = "0.1"

[dev-dependencies]
clap = "~4.0"
rustyline = "10"
rustyline-derive = "0.9.0"
nix = "0.26.2"
