[package]
name = "milu"
version = "0.1.0"
edition = "2018"

[dependencies]
nom = "7"
# nom_locate = "3.0.2"
regex = "1"
dyn-clone = "1"
clap = "~2.33"
easy-error = "1"

[dev-dependencies]
rustyline = "9"
rustyline-derive = "0.5.0"
nix = "0.22.0"
