apiVersion: v1alpha
kind: ProxyDefinition

listeners:
  - name: http
    bind: 0.0.0.0:8081
    tls:
      cert: test.crt
      key: test.key

  - name: tproxy
    bind: 0.0.0.0:8080

connectors:
  - name: direct

rules:
  - filter: domain.end_with("google.com") && family == ipv4
    target: direct
  - target: direct
