apiVersion: v1alpha
kind: ProxyDefinition

listeners:
  - name: tproxy
    bind: 0.0.0.0:8080
  - name: http
    bind: 0.0.0.0:8081
  - name: https
    type: http
    bind: 0.0.0.0:8082
    tls:
      cert: test.crt
      key: test.key
  - name: socks
    bind: 0.0.0.0:1080
    auth:
      required: true
      users:
        - username: a
          password: a

connectors:
  - name: direct
  - name: http
    server: 192.168.100.1
    port: 8848
  - name: https
    type: http
    server: 192.168.100.1
    port: 3333
    tls:
      insecure: true
      ca: ca.crt
      auth:
        cert: proxy.crt
        key: proxy.key
  - name: socks
    server: 192.168.100.1
    port: 1080
  - name: socks-tls
    type: socks
    server: 192.168.100.1
    port: 9123
    auth:
      username: proxy
      password: fuckgfw
    tls:
      insecure: true

rules:
  - filter: request.source =~ "127.0.0.1" and request.target =~ "google.com"
    target: https
  - filter: request.target =~ "2607:f8b0"
    target: https
  - filter: request.target =~ "deny-me.com"
    # target "deny" is a resvered target name for explicitly deny a matching request
    target: deny
  - target: socks-tls
    # an empty filter means that all requests will be accepted.
    # if no rule matches the request, access will be denied.
